### PR TITLE
Adds example static goal for point robot and nLinkReacher

### PR DESCRIPTION
**Pull request by maxspahn**
Adds very simple static goal to some of the examples.
We must reiterate on the specific requirements for that.
@alxschwrz

### CODE REVIEW

**Review by alxschwrz — CHANGES_REQUESTED** [review]
When trying to run the point_robot.py example with the settings 
```
obstacles = True
goal = True
```
I receive the following error:

_sphereObst1 = SphereObstacle(name="simpleSphere", contentDict=obst1Dict)
TypeError: __init__() got an unexpected keyword argument 'contentDict'_

Same error occurs for nLinkReacher.

Also: It might be nice to add in the documentation for which use cases the [extras] are required in the setup.py file.

**Comment by maxspahn** [comment]
> When trying to run the point_robot.py example with the settings
> 
> ```
> obstacles = True
> goal = True
> ```
> 
> I receive the following error:
> 
> _sphereObst1 = SphereObstacle(name="simpleSphere", contentDict=obst1Dict) TypeError: **init**() got an unexpected keyword argument 'contentDict'_
> 
> Same error occurs for nLinkReacher.
> 
> Also: It might be nice to add in the documentation for which use cases the [extras] are required in the setup.py file.

Dose the problem persist?

**Review by alxschwrz — APPROVED** [review]
Tested examples on my machine (MacOs M1). Needed to reinstall the extra package 'MotionPlanningScenes'.

Point Robot & nLinkReacher examples work with both, static goal and obstacles, for me.

**Comment by maxspahn** [comment]
Did you need to manually install it? Or was it automatically installed through the pip install -r requirements.txt.

**Comment by alxschwrz** [comment]
I needed to delete the MotionPlanningScenes, before I was able to reinstall it using `pip install -r requirement_scenes.txt`. Simply deleting the src-folder in my virtual environment was not sufficient for this though.

To reproduce; the way I was doing it: 
1. Delete the whole (local) branch
2. Checkout the branch "fr-add-goals" locally
3. `pip install -r requirement_scenes.txt `
-> This worked for me.

**Comment by maxspahn** [comment]
This is a reasonable effort that only appears when you have an old version of MotionPlanningScenes. 
Does not happen to fresh installs.

**Pull request merged**
