### PR TITLE
fix lint

### LINKED ISSUE #53: fix variable name
pylint reports some invalid-name such as `_limUpPos`

### PR DESCRIPTION
**Pull request by SkyloveQiu**
fix #53

### CODE REVIEW

**Comment by SkyloveQiu** [comment]
lint report 10/10

**Comment by maxspahn** [comment]
The test failed because the poetry.lock was not updated according to the changes in pyproject.toml.

**Comment by SkyloveQiu** [comment]
okay.

**Comment by SkyloveQiu** [comment]
I think this branch is ready for merge.

**Pull request merged**
