### PR TITLE
Moves sensors inside the source folder of planarenvs, #38.

### PR DESCRIPTION
**Pull request by maxspahn**
@alxschwrz Can you verify that?
Is this really necessary?

### CODE REVIEW

**Comment by alxschwrz** [comment]
Hi @maxspahn,
what exactly should I verify? Is this necessary for installing the package via pip?

**Comment by maxspahn** [comment]
If you install the package using pip. Can you create a script that uses the sensors?

**Comment by alxschwrz** [comment]
@maxspahn it is already merged anyway, but I can confirm it now. Sensor (before this PR) was not installed when using pip. I struggled quite some hours yesterday before I managed to understand this.

**Comment by maxspahn** [comment]
General note: python packages are usually following the repository structure
- repository-root
  - package-src
     - content of package
  - examples
  - docs
  - (tests) tests might also be in package-src
  - License
  - Readme
   -pyproject.toml
    - ...

**Comment by alxschwrz** [comment]
Thanks, I did not know that! I was also having the problem, that I was using the package in another repository as a git submodule. However it was referencing the "old" package which I installed via pip. I need to be careful here.

**Pull request merged**
